---
- name: "Configure zrepl when it is defined in inventory"
  when: zrepl is defined
  block:
    - name: "Install required packages"
      vars:
        packages_present: "{{ packages_present_zrepl }}"
        repos:
          - zrepl
        call_from: "role zrepl"
      ansible.builtin.import_role:
        name: "{{ __fqcn_packages_role__ }}"
      tags: install

    - name: "Configure zrepl"
      ansible.builtin.template:
        dest: /etc/zrepl/zrepl.yml
        src: zrepl.yml.j2
      notify: "Restart zrepl"
      tags:
        - config
        - configure